spring.application.name=coinbasekafkaservice

# Kafka (shared)
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

# Coinbase app config
app.coinbase.ws-url=wss://ws-feed.exchange.coinbase.com