# Dev profile – local Kafka and Coinbase config
spring.kafka.bootstrap-servers=10.20.0.202:9092

app.coinbase.topic=coinbase-trades
app.coinbase.product-ids=BTC-USD

# Logging: root INFO; app package DEBUG so AppLogger debug shows in console
logging.level.root=INFO
logging.level.com.nathannli.coinbasekafkaservice=DEBUG