# Prod profile – set your production Kafka broker(s)
spring.kafka.bootstrap-servers=localhost:9092

app.coinbase.topic=coinbase-trades
app.coinbase.product-ids=BTC-USD

# Logging: root WARN; app package WARN so AppLogger warn shows in console
logging.level.root=WARN
logging.level.com.nathannli.coinbasekafkaservice=WARN