spring.application.name=coinbasekafkaservice

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

# Coinbase app config
app.coinbase.ws-url=wss://ws-feed.exchange.coinbase.com
app.coinbase.topic=coinbase-trades
app.coinbase.product-ids=BTC-USD
